[package]
authors = ["Ryan Campbell <rdcampbell1990@gmail.com>"]
name = "gadget_nes"
version = "0.2.0"

[dependencies]
bitflags = "0.7.0"
sdl2 = "0.21.0"

[features]
default = []

debug_cpu = []
debug_ppu = []
